# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Factory')),
            ],
        ),
    ]
