# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_factory_good_payment_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='id_client',
        ),
    ]
