# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181218_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment1',
            name='nds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment1',
            name='price_nds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payment1',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
