# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20181218_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
