# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id_client',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
